# Generated by Django 3.2.10 on 2022-01-19 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('positions', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('min_qualification', models.TextField(blank=True, null=True)),
                ('min_experience', models.IntegerField(null=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('extra_fields', models.TextField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
